version: '3'

services:
# https://github.com/alexanderschnitzler/docker-mysqldump
  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    container_name: providers-web
    image: providers
    working_dir: /code
    volumes:
      - ./:/code
  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: providers-nginx
    restart: always
    ports:
       - "8585:80"
    volumes:
      - ./:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
